/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package defense_system;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;

/**
 *
 * @author hp
 */
public class Submarine extends javax.swing.JFrame implements InnerDefense_System {

    /**
     * Creates new form Submarine
     */
    public void scroll20(){
        shootSub.setEnabled(true);
    }
    public void scroll40(){
        sonarSub.setEnabled(true);
    }
    public void scroll60(){
        tomohawkSub.setEnabled(true);
    }
    public void scroll80(){
        tridentSub.setEnabled(true);
    }
    public void scrollBelow20(){
        shootSub.setEnabled(false);
        sonarSub.setEnabled(false);
        tomohawkSub.setEnabled(false);
        tridentSub.setEnabled(false);
    }
    public void scrollBelow40(){
        sonarSub.setEnabled(false);
        tomohawkSub.setEnabled(false);
        tridentSub.setEnabled(false);
    }
    public void scrollBelow60(){
        tomohawkSub.setEnabled(false);
        tridentSub.setEnabled(false);
    }
    public void scrollBelow80(){
        tridentSub.setEnabled(false);
    }
    public void receiveMessageFrommain(String message){
        messageReceiveSub.setText(messageReceiveSub.getText().equals("")?message:"\n"+message);
    }
    public void receiveMessageFrommainHelicopter(String message){}
    public void receiveMessageFrommainSubmarine(String message){
        messageReceiveSub.setText(messageReceiveSub.getText().equals("")?message:"\n"+message);}
    public void receiveMessageFrommainTank(String message){}
    public void areaClearSend(){
        areaClearSub.setText("Area Cleared");
    }
    public void areaNotClear(){
        areaClearSub.setText("Area Not Cleared");
    }
    public void assignLinkToMain(MainController mainController){
        this.mainController=mainController;
    }
    public void sendInformationHelicopter(){
        
    }
    public void sendInformationSubmarine(){
        int valueS = (Integer) countingSoldiersSub.getValue();
        int valueA = (Integer) countingAmmoSub.getValue();
        int valueF = (Integer) fuelCount.getValue();
        int eLevel = energySliderSub.getValue();
        int oLevel = OxygenSliderSub.getValue();
        boolean position = positionSub.isSelected();
        String notifyPosition = position?"In position":"Not in position";
        mainController.updateSoldierCount(valueS,valueA,valueF,eLevel,oLevel,notifyPosition,"S");
    }
    public void sendInformationTank(){}
    
    private MainController mainController;

    public Submarine() {
        initComponents();
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ammoCountSub = new javax.swing.JLabel();
        tridentSub = new javax.swing.JButton();
        countingSoldiersSub = new javax.swing.JSpinner();
        countingAmmoSub = new javax.swing.JSpinner();
        positionSub = new javax.swing.JCheckBox();
        OxygenSliderSub = new javax.swing.JSlider();
        areaClearSub = new javax.swing.JLabel();
        shootSub = new javax.swing.JButton();
        sonarSub = new javax.swing.JButton();
        typeMessageSub = new javax.swing.JTextField();
        tomohawkSub = new javax.swing.JButton();
        sendingMessageSub = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        messageReceiveSub = new javax.swing.JTextArea();
        soldierCountSub = new javax.swing.JLabel();
        energySliderSub = new javax.swing.JSlider();
        energyLabelSub = new javax.swing.JLabel();
        oxygenLabelSub = new javax.swing.JLabel();
        fuelLabel = new javax.swing.JLabel();
        fuelCount = new javax.swing.JSpinner();

        setTitle("Submarine");
        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ammoCountSub.setText("Ammo count");

        tridentSub.setText("Trident-2 missile");
        tridentSub.setEnabled(false);
        tridentSub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tridentSubActionPerformed(evt);
            }
        });

        positionSub.setText("Position");

        OxygenSliderSub.setMajorTickSpacing(20);
        OxygenSliderSub.setMinorTickSpacing(5);
        OxygenSliderSub.setOrientation(javax.swing.JSlider.VERTICAL);
        OxygenSliderSub.setPaintLabels(true);
        OxygenSliderSub.setPaintTicks(true);
        OxygenSliderSub.setValue(100);

        areaClearSub.setText("Area not cleared");

        shootSub.setText("Shoot");
        shootSub.setEnabled(false);

        sonarSub.setText("Sonar operation");
        sonarSub.setEnabled(false);

        typeMessageSub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                typeMessageSubActionPerformed(evt);
            }
        });

        tomohawkSub.setText("Tomohawk missile");
        tomohawkSub.setEnabled(false);

        sendingMessageSub.setText("Send");

        messageReceiveSub.setColumns(20);
        messageReceiveSub.setRows(5);
        jScrollPane1.setViewportView(messageReceiveSub);

        soldierCountSub.setText("Soldier count");

        energySliderSub.setMajorTickSpacing(20);
        energySliderSub.setMinorTickSpacing(5);
        energySliderSub.setOrientation(javax.swing.JSlider.VERTICAL);
        energySliderSub.setPaintLabels(true);
        energySliderSub.setPaintTicks(true);
        energySliderSub.setValue(100);

        energyLabelSub.setText("Energy");

        oxygenLabelSub.setText("Oxygen");

        fuelLabel.setText("Fuel amount");

        sendingMessageSub.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt){
                String message = "Submarine : "+typeMessageSub.getText();
                mainController.getMessage(message);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(typeMessageSub, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(sendingMessageSub, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(positionSub, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(areaClearSub, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(196, 196, 196)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(soldierCountSub, javax.swing.GroupLayout.DEFAULT_SIZE, 82, Short.MAX_VALUE)
                                    .addComponent(fuelLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(37, 37, 37))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(shootSub, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(tomohawkSub, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tridentSub, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(sonarSub, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(34, 34, 34)
                                .addComponent(ammoCountSub, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                                .addGap(31, 31, 31)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(countingAmmoSub)
                            .addComponent(countingSoldiersSub, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                            .addComponent(fuelCount))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(energyLabelSub, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(energySliderSub, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(71, 71, 71)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(oxygenLabelSub, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(OxygenSliderSub, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(areaClearSub, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(soldierCountSub)
                                .addComponent(countingSoldiersSub, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(energyLabelSub)
                            .addComponent(oxygenLabelSub))
                        .addGap(15, 15, 15)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(shootSub)
                                    .addComponent(sonarSub))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tomohawkSub))
                            .addComponent(tridentSub, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(countingAmmoSub, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ammoCountSub))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(fuelLabel)
                                    .addComponent(fuelCount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(20, 20, 20)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(77, 77, 77)
                                .addComponent(positionSub)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(typeMessageSub, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sendingMessageSub)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(OxygenSliderSub, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(energySliderSub, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tridentSubActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tridentSubActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tridentSubActionPerformed

    private void typeMessageSubActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_typeMessageSubActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_typeMessageSubActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Submarine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Submarine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Submarine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Submarine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
              //  new Submarine().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSlider OxygenSliderSub;
    private javax.swing.JLabel ammoCountSub;
    private javax.swing.JLabel areaClearSub;
    private javax.swing.JSpinner countingAmmoSub;
    private javax.swing.JSpinner countingSoldiersSub;
    private javax.swing.JLabel energyLabelSub;
    private javax.swing.JSlider energySliderSub;
    private javax.swing.JSpinner fuelCount;
    private javax.swing.JLabel fuelLabel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea messageReceiveSub;
    private javax.swing.JLabel oxygenLabelSub;
    private javax.swing.JCheckBox positionSub;
    private javax.swing.JButton sendingMessageSub;
    private javax.swing.JButton shootSub;
    private javax.swing.JLabel soldierCountSub;
    private javax.swing.JButton sonarSub;
    private javax.swing.JButton tomohawkSub;
    private javax.swing.JButton tridentSub;
    private javax.swing.JTextField typeMessageSub;
    // End of variables declaration//GEN-END:variables
}
