/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package defense_system;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;

/**
 *
 * @author hp
 */
public class Tank extends javax.swing.JFrame implements InnerDefense_System {

    /**
     * Creates new form Tank
     */
    public void scroll20(){
        shootTank.setEnabled(true);
    }
    public void scroll40(){
        missiletank.setEnabled(true);
    }
    public void scroll60(){
        radarTank.setEnabled(true);
    }
    public void scroll80(){
        rotateTank.setEnabled(true);
    }
    public void scrollBelow20(){
        shootTank.setEnabled(false);
        missiletank.setEnabled(false);
        radarTank.setEnabled(false);
        rotateTank.setEnabled(false);
    }
    public void scrollBelow40(){
        missiletank.setEnabled(false);
        radarTank.setEnabled(false);
        rotateTank.setEnabled(false);
    }
    public void scrollBelow60(){
        radarTank.setEnabled(false);
        rotateTank.setEnabled(false);
    }
    public void scrollBelow80(){
        rotateTank.setEnabled(false);
    }
    public void receiveMessageFrommain(String message){
        messagereceivetank.setText(messagereceivetank.getText().equals("")?message:"\n"+message);
    }
    public void receiveMessageFrommainHelicopter(String message){}
    public void receiveMessageFrommainSubmarine(String message){}
    public void receiveMessageFrommainTank(String message){
        messagereceivetank.setText(messagereceivetank.getText().equals("")?message:"\n"+message);
    }
    public void areaClearSend(){
        areaCleartank.setText("Area Cleared");
    }
    public void areaNotClear(){
        areaCleartank.setText("Area Not Cleared");
    }
    public void assignLinkToMain(MainController mainController){
        this.mainController=mainController;
    }
    public void sendInformationHelicopter(){
        
    }
    public void sendInformationSubmarine(){
        
    }
    public void sendInformationTank(){
        int valueS = (Integer) countingSoldiersTank.getValue();
        int valueA = (Integer) countingAmmoTank.getValue();
        int valueF = (Integer) fuelCount.getValue();
        int eLevel = sloderTank.getValue();
        boolean position = positionTank.isSelected();
        String notifyPosition = position?"In position":"Not in position";
        mainController.updateSoldierCount(valueS,valueA,valueF,eLevel,0,notifyPosition,"T");
    }
    
    private MainController mainController;

    public Tank() {
        initComponents();
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        messageTypingTank = new javax.swing.JTextField();
        messageSendTank = new javax.swing.JButton();
        soldierTank = new javax.swing.JLabel();
        ammoTank = new javax.swing.JLabel();
        countingSoldiersTank = new javax.swing.JSpinner();
        countingAmmoTank = new javax.swing.JSpinner();
        positionTank = new javax.swing.JCheckBox();
        sloderTank = new javax.swing.JSlider();
        areaCleartank = new javax.swing.JLabel();
        shootTank = new javax.swing.JButton();
        missiletank = new javax.swing.JButton();
        radarTank = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        messagereceivetank = new javax.swing.JTextArea();
        rotateTank = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        fuelCount = new javax.swing.JSpinner();

        setTitle("Tank");
        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        messageSendTank.setText("Send");

        soldierTank.setText("Soldier count");

        ammoTank.setText("Ammo count");

        positionTank.setText("Position");

        sloderTank.setMajorTickSpacing(20);
        sloderTank.setMinorTickSpacing(5);
        sloderTank.setOrientation(javax.swing.JSlider.VERTICAL);
        sloderTank.setPaintLabels(true);
        sloderTank.setPaintTicks(true);
        sloderTank.setValue(100);

        areaCleartank.setText("Area not cleared");

        shootTank.setText("Shoot");
        shootTank.setEnabled(false);

        missiletank.setText("Missile operation");
        missiletank.setEnabled(false);

        radarTank.setText("Radar operation");
        radarTank.setEnabled(false);

        messagereceivetank.setColumns(20);
        messagereceivetank.setRows(5);
        jScrollPane1.setViewportView(messagereceivetank);

        rotateTank.setText("Rotate shooting");
        rotateTank.setEnabled(false);
        rotateTank.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rotateTankActionPerformed(evt);
            }
        });

        jLabel1.setText("Fuel amount");

        messageSendTank.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt){
                String message = "Tank : "+messageTypingTank.getText();
                mainController.getMessage(message);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(messageTypingTank, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(messageSendTank, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1))
                        .addGap(18, 18, 18)
                        .addComponent(positionTank, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(shootTank, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(radarTank, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(rotateTank, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(missiletank, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(areaCleartank, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(51, 51, 51)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(soldierTank, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(ammoTank, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fuelCount, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(countingSoldiersTank)
                                .addComponent(countingAmmoTank, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addComponent(sloderTank, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(areaCleartank, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(shootTank)
                            .addComponent(missiletank))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(radarTank))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(soldierTank)
                            .addComponent(countingSoldiersTank, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(countingAmmoTank, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ammoTank))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rotateTank, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel1)
                                .addComponent(fuelCount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(positionTank)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(messageTypingTank, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(messageSendTank))
                        .addContainerGap())))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addComponent(sloderTank, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rotateTankActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rotateTankActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rotateTankActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tank.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tank.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tank.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tank.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               // new Tank().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ammoTank;
    private javax.swing.JLabel areaCleartank;
    private javax.swing.JSpinner countingAmmoTank;
    private javax.swing.JSpinner countingSoldiersTank;
    private javax.swing.JSpinner fuelCount;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton messageSendTank;
    private javax.swing.JTextField messageTypingTank;
    private javax.swing.JTextArea messagereceivetank;
    private javax.swing.JButton missiletank;
    private javax.swing.JCheckBox positionTank;
    private javax.swing.JButton radarTank;
    private javax.swing.JButton rotateTank;
    private javax.swing.JButton shootTank;
    private javax.swing.JSlider sloderTank;
    private javax.swing.JLabel soldierTank;
    // End of variables declaration//GEN-END:variables
}
